- hosts: all
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: nginx-demo, tags: nginx-demo }

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Raspi is ready now!"
