---
# tasks file for rpi-nextcloud
- name: Log on which Linux distro Docker is going to be installed
  debug:
    msg: "The distro is: {{ ansible_distribution|lower }} and the version name is: {{ ansible_distribution_release }}"

- name: Update apt packages
  become: true
  apt:
    upgrade: no
    update_cache: yes
    autoremove: yes
    cache_valid_time: 86400 #One day

#- name: Reboot
#  reboot:
#    msg: Reboot to prevent hanging docker installation after apt upgrade

- name: Install a list of packages [{{ pkgstoinstall }}]
  apt:
    name: "{{ pkgstoinstall }}"
    state: latest
    allow_unauthenticated: true
    update_cache: yes
    autoremove: yes
#- name: Add Docker apt key
#  apt_key:
#    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
#    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
#    state: present
#  ignore_errors: true

#- name: Add Docker apt repo (as shown in step 4 of https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository in armhf)
#  shell: |
#    echo "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution|lower }} \
#    {{ ansible_distribution_release }} stable" | \
#    sudo tee /etc/apt/sources.list.d/docker.list
#  become: true

#- name: Remove python-configparser package
#  apt:
#    name: python-configparser
#    state: absent

- name: get docker convenience script
  shell: curl -fsSL https://get.docker.com -o get-docker.sh
  args:
    creates: /home/pi/get-docker.sh

- name: install docker
  shell: sh /home/pi/get-docker.sh
  args:
    creates: /usr/bin/docker

- name: make pi user execute docker commands
  shell: usermod -aG docker pi

- name: install docker-compose
  shell: pip3 -v install docker-compose
  args:
    creates: /usr/local/bin/docker-compose

