---
# tasks file for nginx-demo
- name: Create installation dir
  file:
    path: "{{ workdir }}"
    state: directory
- name: Template docker-compose.yaml
  template:
    src: docker-compose.yaml
    dest: "{{ workdir }}"

- name: Copy src folder
  copy:
    src: src
    dest: "{{ workdir }}"

- name: Start up nginx
  shell: docker-compose up -d
  args:
    chdir: /opt/nginx